# Basic set up for package managers
version: 2
updates:
    - package-ecosystem: "gomod"
      directory: "/go"
      reviewers:
        - "data-engineering-samples/reviewers"
      schedule:
        interval: "daily"
