# Basic set up for package managers
version: 2
updates:
    - package-ecosystem: "gomod"
      directory: "/go"
      reviewers:
        - "data-engineering-samples/reviewers"
      schedule:
        interval: "daily"
      # Disable version updates for gomod dependencies. This option has no impact on security updates
      open-pull-requests-limit: 0
    - package-ecosystem: "pip"
      directory: "/python"
      reviewers:
        - "data-engineering-samples/reviewers"
      schedule:
        interval: "daily"
      # Disable version updates for pip dependencies. This option has no impact on security updates
      open-pull-requests-limit: 0
