name: PR Approvals Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-approvals:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR approvals
      run: |
        APPROVALS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                     -H "Accept: application/vnd.github.v3+json" \
                     "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.number }}/reviews" \
                   | jq -r '.[] | select(.state == "APPROVED") | .user.login')

        ALL_REVIEWERS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.number }}" \
                        | jq -r '.requested_reviewers[]')

        if [ "$(echo "$APPROVALS" | sort)" == "$(echo "$ALL_REVIEWERS" | sort)" ]; then
          echo "All reviewers have approved the PR."
        else
          echo "Not all reviewers have approved the PR."
          exit 1
        fi
